import React, { useState, useEffect, useRef } from "react";
import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import st from "../../styles/[userId]/home.module.scss";
import { useUser } from "@auth0/nextjs-auth0";

import MainNav from "../../components/reusables/MainNav";
import HomeTop from "../../components/home/HomeTop";
import { RootState } from "../../redux/store";
import { useGetUserByUserIdQuery } from "../../redux/query/userQuery";
import { setUserId } from "../../redux/supporterSlice";
import { GetServerSideProps } from "next";
import NotLoggedIn from "../../components/reusables/NotLoggedIn";

const Home = (props: { userId: string }) => {
  const [titleName, setTitleName] = useState("");

  const didEffect = useRef(false);
  const supporter = useSelector((state: RootState) => state.supporter);
  const dispatch = useDispatch();
  const userController = useUser();
  const { data, error, isFetching } = useGetUserByUserIdQuery(props.userId, {
    skip: supporter.isSkip,
  });

  useEffect(() => {
    if (props.userId && !didEffect.current) {
      didEffect.current = true;
      dispatch(setUserId(props.userId));
    }

    if (data?.userName) setTitleName(data?.userName);
  }, [data?.userName, dispatch, props.userId]);

  if (!userController.user) {
    return (
      <>
        <Head>
          <title>ログインし直してください</title>
        </Head>

        <NotLoggedIn />
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>{`しょしまる図書館-エントランス`}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div
          className={st.home}
          style={{ overflow: supporter.isNavMove ? "hidden" : "scroll" }}
        >
          <MainNav />

          <HomeTop />
        </div>
      </>
    );
  }
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const props = { userId: "" };

  if (context.params && typeof context.params.userId === "string") {
    props.userId = context.params.userId;
  }
  return { props: props };
};

export default Home;
