import React from "react";
import { NextPage } from "next";
import Head from "next/head";
import { useSelector } from "react-redux";

import { RootState } from "../redux/store";
import MainNav from "../components/reusables/MainNav";
import st from "../styles/connection.module.scss";

const Connection: NextPage = () => {
  const supporter = useSelector((state: RootState) => state.supporter);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={st.connectionTop}
        style={{ overflow: supporter.isNavMove ? "hidden" : "scroll" }}
      >
        <MainNav />

        <main className={st.connection}>
          <div className={st.cordCard}>
            <span className={st.text}>そしまるの連携コードは</span>
            <span className={st.cord}>2971</span>
            <span className={st.text}>です。</span>
          </div>

          <div className={st.descContainer}>
            <div className={st.descTitle}>
              <span className={st.title}>連携の方法</span>
              <div className={st.titleLine}></div>
            </div>

            <div>連携</div>
          </div>

          <div className={st.bottomSpace} />
        </main>
      </div>
    </>
  );
};

export default Connection;
