import type { NextPage } from "next";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Link from "next/link";
import axios from "axios";
import { useUser } from "@auth0/nextjs-auth0";
import st from "../styles/index.module.scss";

const Home: NextPage = () => {
  const { user, error, isLoading } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (error) {
      router.push("/error");
    }

    if (user) {
      axios.get(`/api/user/get/email/${user.email}`).then((data) => {
        if (data.data.userId) {
          if (data.data.status.isAdmin) {
            router.push("/admin/home");
          } else {
            router.push(`/${data.data.userId}/home`);
          }
        } else {
          router.push("/welcome");
        }
      });
    }
  }, [error, router, user]);

  if (isLoading) return <div>loading</div>;

  return (
    <>
      <Head>
        <title>しょしまる図書館入り口</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={st.logoutTop}>
        <div className={st.logo}>LOGO</div>

        <div className={st.title}>しょしまる図書館</div>

        <Link href="/api/auth/login" passHref={true}>
          <button className={st.loginBtn}>ログイン</button>
        </Link>
      </main>
    </>
  );
};

export default Home;
