import React from "react";
import { NextPage } from "next";
import { useSelector } from "react-redux";
import Head from "next/head";

import MainNav from "../components/reusables/MainNav";
import RequestTop from "../components/request/RequestTop";
import { RootState } from "../redux/store";

const Request: NextPage = () => {
  const supporter = useSelector((state: RootState) => state.supporter);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ overflow: supporter.isNavMove ? "hidden" : "scroll" }}>
        <MainNav />

        <RequestTop />
      </div>
    </>
  );
};

export default Request;
