import { useEffect, useState, useRef, FormEvent } from "react";
import type { NextPage } from "next";
import { useRouter } from "next/router";
import Head from "next/head";
import Cookie from "js-cookie";
import { toast } from "react-toastify";
import st from "../styles/welcome.module.scss";
import { UserType } from "../redux/globalType";
import axios from "axios";
import { useUser } from "@auth0/nextjs-auth0";

const Welcome: NextPage = () => {
  const [userArr, setUserArr] = useState<UserType[]>([]);
  const [userId, setUserId] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const didEffect = useRef(false);
  const { user } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (!didEffect.current) {
      didEffect.current = true;

      axios.get("/api/user/get/notRegister").then((item) => {
        item.data.map((el: UserType, i: number) => {
          if (i === 0) setUserId(el.userId);
          setUserArr((prevState) => [...prevState, el]);
        });
      });
    }
  }, []);

  const nameChange = (e: FormEvent<HTMLSelectElement>) => {
    setUserId(e.currentTarget.value);
  };

  const desideClick = () => {
    if (Cookie.get("lineId")) {
      setIsLoading(true);

      axios
        .post("/api/user/update/register", {
          userId: userId,
          email: user?.email,
          lineId: Cookie.get("lineId"),
        })
        .then((item) => {
          Cookie.remove("lineId");
          return router.push(`/${item.data}/home`);
        })
        .catch((err) => console.log(err));
    } else {
      toast(
        "正しい入り口から入ってきましたか？入場処理ができません。CookieをONにしてください。"
      );
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={st.welcomeTop}>
        <div className={st.logo}>LOGO</div>

        <div className={st.introText}>
          改めてぼくはしょしまる！
          <br />
          そしまるの兄だよ。
          <br />
          よろしくね！
          <br />
          数ヶ月前、弟のそしまるがどこかに行ってしまって調べたら
          <br />
          ここにたどり着いたんだ。
          <br />
          ぼくは本が読むのが好きで
          <br />
          ここでも本を読みたいな～って思ったから
          <br />
          自分の図書館を作ったんだ。
          <br />
          ここの図書館にはぼくの好きな医学の本をかき集めたんだ。
          <br />
          とっても幸せ！
          <br />
          この性格が功を奏してか
          <br />
          故郷の医学部でBrainとしてたくさんの友人を救ったんだ～
          <br />
          これはちょっとした自慢だよ！
          <br />
          最近、みかんという果物を初めて食べたんだけど
          <br />
          これめっちゃ甘酸っぱくて美味しいね～
          <br />
          だからこの図書館にオレンジ色をたくさん使ったんだよ～
          <br />
          <br />
          あぁ…
          <br />
          ぼくばっかりしゃべりすぎたなぁ
          <br />
          ぼく、君のことも知りたい！
          <br />
          君の名前を教えてくれるかな？
        </div>

        <div className={st.inputArea}>
          <div className={st.inputIndication}>自分の名前を下から選んでね。</div>
          <select
            name="selectUserName"
            id="userName"
            className={st.selectName}
            onChange={nameChange}
            disabled={isLoading}
          >
            {userArr.map((el, i) => (
              <option key={i} value={el.userId}>
                {el.userName}
              </option>
            ))}
          </select>

          <button
            className={st.desideBtn}
            onClick={desideClick}
            disabled={isLoading}
          ></button>
        </div>
      </main>
    </>
  );
};

export default Welcome;
